version: '3.8'
services:
  reencode_job:
    image: python-ffmpeg
    container_name: reencode_job
    privileged: true
    volumes:
      - /home/larsluph/reencode_job:/app
      - /home/larsluph/videos:/data
    command: ['python3', '/app/main.py', '/data']
