services:
  reencode_job:
    image: ghcr.io/larsluph/reencode_job
    container_name: reencode_job
    privileged: true
    volumes:
    - "/home/larsluph/reencode_job/logs:/app/logs"
    - "/home/larsluph/reencode_job/lock:/app/lock"
    - "/home/larsluph/videos:/data"
    command: ['/data']
